/**
 * 项目配置常量
 */

// ==================== 移动端配置 ====================
export const TDESIGN_MOBILE_GROUP: string[] = [
    'Vant', 'Uni-app', 'Taro'
]

export const TDESIGN_MOBILE_PROJECTS: string[] = [
  'tdesign-miniprogram',
  'tdesign-mobile-vue',
  'tdesign-mobile-react',
  'tdesign-qq-miniprogram',
  'tdesign-uniapp',
  'tdesign-uniapp-chat',
  'tdesign-flutter',
  '@tdesign/uniapp',
  '@tdesign/uniapp-chat',
  '@tencent/tdesign-vue-mobile',
  '@tencent/tdesign-miniprogram-chat',
]

export const MOBILE_PROJECT_PREFIXES: string[] = [
  'antd-mobile',
  'antd-mini',
  '@tencent/tea-component-taro',
  '@tencent/tea-component-mobile',
  '@arco-design/mobile-react',
  '@tencent/weui-liteapp',
  '@tencent/weui-miniprogram',
  'weui-miniprogram',
  ...TDESIGN_MOBILE_PROJECTS,
]

// ==================== 桌面端配置 ====================

export const TDESIGN_PC_PROJECTS: string[] = [
  '@tdesign-atomic/demos-react',
  '@tdesign-atomic/demos-svelte',
  '@tdesign-atomic/demos-vue',
  '@tdesign-atomic/site-react',
  '@tdesign-atomic/site-shared',
  '@tdesign-atomic/site-svelte',
  '@tdesign-atomic/site-vue',
  '@tdesign-mcp-server/common',
  '@tdesign-react/aigc',
  '@tdesign-react/chat',
  '@tdesign-vue-next/auto-import-resolver',
  '@tdesign-vue-next/chat',
  '@tdesign-vue-next/nuxt',
  '@tdesign/common',
  '@tdesign/common-docs',
  '@tdesign/common-js',
  '@tdesign/common-style',
  '@tdesign/components',
  '@tdesign/icons-svelte',
  '@tdesign/internal-utils',
  '@tdesign/react-site',
  '@tdesign/shared-hooks',
  '@tdesign/shared-utils',
  '@tdesign/site-components',
  '@tencent/tdesign-angular',
  '@tencent/tdesign-atomic-internal',
  '@tencent/tdesign-atomic-shared',
  '@tencent/tdesign-chatbot',
  '@tencent/tdesign-chatbot-dev',
  '@tencent/tdesign-chatbot-react',
  '@tencent/tdesign-icons-react',
  '@tencent/tdesign-icons-vue',
  '@tencent/tdesign-preset-tailwind',
  '@tencent/tdesign-preset-unocss',
  '@tencent/tdesign-react',
  '@tencent/tdesign-react-gy',
  '@tencent/tdesign-tailwind-react',
  '@tencent/tdesign-tailwind-vue',
  '@tencent/tdesign-tailwind4-react',
  '@tencent/tdesign-tailwind4-vue',
  '@tencent/tdesign-theme-tea',
  '@tencent/tdesign-tokens',
  '@tencent/tdesign-unocss-react',
  '@tencent/tdesign-unocss-svelte',
  '@tencent/tdesign-unocss-vue',
  '@tencent/tdesign-vue',
  '@tencent/tdesign-vue-chat',
  '@tencent/tdesign-vue-next',
  '@tencent/unocss-preset-tdesign',
  'tdesign-icons-angular',
  'tdesign-icons-react',
  'tdesign-icons-react-tea',
  'tdesign-icons-svg',
  'tdesign-icons-view',
  'tdesign-icons-vue',
  'tdesign-icons-vue-next',
  'tdesign-icons-web-components',
  'tdesign-publish-cli',
  'tdesign-react',
  'tdesign-site-components',
  'tdesign-starter-cli',
  'tdesign-theme-generator',
  'tdesign-vue',
  'tdesign-vue-next',
  'tdesign-web-components',
]
